#! /bin/bash

readonly url="${1}"
readonly list=$(mktemp)

if [[ -z "${2}" ]]; then
  echo "Jobs parameter not set, using default of $(nproc)"
  readonly jobn=$(nproc)
else
  echo "Jobs parameter set to ${2}"
  readonly jobn="${2}"
fi

curl "${url}"|\
  awk -F'[\"|<|>]' '/<\/a>/{print $3}'|\
  grep -v ^$|\
  while read -r line; do
    echo "${url}${line}" >> "${list}"
  done

echo "Index at ${list} generated, running aria with $(nproc) jobs."
aria2c --follow-torrent=false\
       --check-certificate=false\
        -Rcj "${jobn}" -m 0 -i "${list}"

echo "Download complete, removing ${list}."
rm -rfv "${list}"
