#! /bin/sh
#
url="$1"
list=$(mktemp)

curl "${url}"|\
	awk -F'[\"|<|>]' '/<\/a>/{print $3}'|grep -v ^$|\
	sed -s "s|^|$url|" > "${list}"
  aria2c --check-certificate=false -R -c -j "$(nproc)" -m 0 -i "${list}"
rm -rfv "${list}"
