#!/bin/bash
#
steps=12
max=$(cat "/sys/class/backlight/"*"/max_brightness")
current=$(cat "/sys/class/backlight/"*"/brightness")
offset=$(( max / steps ))

# Argument Parsing
case "$1" in
  '-i'|'--increase')
    adjusted=$((current + offset))
    ;;
  '-d'|'--decrease')
    adjusted=$((current - offset))
    ;;
  *)
    echo 'Improper usage'
    exit 1
  ;;
esac

# Limits checking
if [[ ${adjusted} -gt ${max} ]]; then
  # If the current brightness + 1 step would be higher than max, apply max
  adjusted="${max}"
fi
if [[ ${adjusted} -le 0 ]]; then
  # If current brightness - 1 step would be >= 0, do nothing
  adjusted="${current}"
fi

# Run the actual command
for backlight_descriptor in /sys/class/backlight/*/brightness; do
  echo "${adjusted}" > "${backlight_descriptor}"
done
