#!/bin/bash
battery_level="$(cat /sys/class/power_supply/BAT0/capacity)"
ac_status="$(cat /sys/class/power_supply/BAT0/status)"

if [[ "${ac_status}" == 'Discharging' && "${battery_level}" -lt 30 ]]; then
	notify-send -u critical "Battery is Low." "Level: $battery_level% "
fi
