#!/bin/bash
#
# volume - dzen volume bar
#

#Customize this stuff
IF="$3" # audio channel: Master|PCM
CARD="$4"
SECS="1"            # sleep $SECS
BG="#151515"        # background colour of window
FG="#eeeeee"        # foreground colour of text/icon
BAR_FG_MUTEoff="#808080"    # foreground colour of volume bar
BAR_FG_MUTEon="#AA3333"    # foreground colour of volume bar
BAR_BG="#090909"    # background colour of volume bar
XPOS=$(xdotool getmouselocation|sed 's/:/ /g'|awk '{print $2}') # h position
YPOS=$(xdotool getmouselocation|sed 's/:/ /g'|awk '{print $4}') # v position
HEIGHT="40"         # window height
WIDTH="200"         # window width
BAR_WIDTH="170"     # width of volume bar
FONT="-*-clean-*-*-*-*-*-*-*-*-*-*-*-*"

#Probably do not customize
PIPE="/tmp/dvolpipe"

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: dvol [option] [argument] [interface] [card]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -h, --help     - display this"
  exit
}

#Argument Parsing
case "$1" in
  '-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%+"
    ;;
  '-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%-"
    ;;
  '-t'|'--toggle')
    AMIXARG="toggle"
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac

#Actual volume changing (readability low)
AMIXOUT="$(amixer -c "$CARD" set "$IF" "$AMIXARG" | tail -n 1)"
MUTE="$(awk -F"[][{}]" '{print $6}' <<<"$AMIXOUT")"
VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
if [ ! -e "$PIPE" ]; then
  mkfifo "$PIPE"
  (dzen2 -tw "$WIDTH" -h "$HEIGHT" -x "$XPOS" -y "$YPOS" -fn "$FONT" -bg "$BG" -fg "$FG" < "$PIPE"
   rm -f "$PIPE") &
fi

#Feed the pipe!
BAR_FG=BAR_FG_MUTE$MUTE
BAR_FG=${!BAR_FG}
(echo "$VOL" | gdbar -fg "$BAR_FG" -bg "$BAR_BG" -w "$BAR_WIDTH" ; sleep "$SECS") > "$PIPE"
