#!/bin/bash

if [ -z $1 ]; then
  find $(readlink -f ~/) -type d -name .git -exec sh -c "cd \"{}\"/../ && pwd && git pull" \;
  exit 0
else
	REPOSITORIES=$(readlink -f $1)
fi

IFS=$'\n'

for REPO in `ls "$REPOSITORIES/"`
do
  if [ -d "$REPOSITORIES/$REPO" ]
  then
    if [ -d "$REPOSITORIES/$REPO/.git" ]
    then
      cd "$REPOSITORIES/$REPO"
      git pull&
    else
      echo "Skipping because it doesn't look like it has a .git folder."
    fi
    echo
  fi
done

wait
