#! /bin/bash
#
# intsize.sh
#
# Distributed under terms of the MIT license.
#
# This script uses the pythagoream theorem to determine font size for the interface of your system.
# It has been tuned for my eyes, if you find it annoying, or hard to read, you'll have to
# adjust the formulas.

source ~/.envrc

xres=$(xdpyinfo | grep dimensions | awk '{print $2}' | awk -F "x" '{print $1}')
yres=$(xdpyinfo | grep dimensions | awk '{print $2}' | awk -F "x" '{print $2}')
combres=$((xres * yres))
squareddots=$(($measureddots**2))
combsquare=$((combres / squareddots))
squaredpix=$(bc <<< "scale=0; sqrt($((combsquare)))")
c=$((squaredpix + distance))
b=$((squaredpix))
fontsize=$(bc <<< "scale=0; sqrt($(($((c**2)) - $((b**2)))))")

echo "Font set to $fontname $fontsize"
xrandr --dpi $measureddots
sed -i "s/gtk-font-name=.*/gtk-font-name=$fontname $fontsize/g" ~/.config/gtk-3.0/settings.ini
sed -i "s/gtk-font-name=.*/gtk-font-name=\"$fontname $fontsize\"/g" ~/.gtkrc-2.0
gsettings set org.gnome.desktop.interface document-font-name "$fontname $fontsize"
gsettings set org.gnome.desktop.interface font-name "$fontname $fontsize"
