#!/bin/bash
basename="$1"
shift
sandbox="$1"
shift
container="${basename}-${sandbox}"
commandline="$@"
fullcommand=(
  sudo -u $sandbox \
    -i DISPLAY=$DISPLAY \
    $commandline
      )

echo "Container:\t $container"
echo "Display:\t $DISPLAY"
echo "Running:\t ${fullcommand[@]}"
sudo lxc-start -Fn $container -- "${fullcommand[@]}"
sudo lxc-stop "$container"
