#!/bin/bash
basename="$1"
shift
sandbox="$1"
shift
container="${basename}-${sandbox}"
commandline="$@"
fullcommand=(
  sudo -HnSu $sandbox \
    -i DISPLAY=$DISPLAY \
    -- $commandline
      )
set -m

echo "Container:\t $container"
echo "Display:\t $DISPLAY"
echo "Running:\t ${fullcommand[@]}"
sudo lxc-start -n $container
sudo lxc-attach -n $container -- "${fullcommand[@]}"
sudo lxc-stop "$container"
