#!/bin/bash

if [ -z $1  ]; then
  echo "Usage: $(basename $0) <command>"
  exit
fi

if [ -z "$(pidof $1)" ]; then
  (screen -d -m -S $1 $1)
  echo "$1 started in background"
else
	(screen -Dr $1)
fi
