#!/bin/bash
TMPFILE=$(mktemp)

pid()
{
  screen -ls|grep $(hostname)|grep 'Detached'|awk -F. '{print $1}'|sed 's/^[ \t]*//'
}

makeList()
{
	for i in $(pid); do
		pstree $i | sed -n "s/^screen/$i/;1p"
	done | awk '{printf("%5d %s\n", NR,$0)}'
}

if [[ -z $(makeList) ]]; then
  echo "There are no detached screens on $(hostname)."
  exit 1
else
	dialog --keep-tite --menu "Choose one:" 15 70 10 \
	    $(makeList) 2>$TMPFILE
	RESULT=$(cat $TMPFILE)
fi

if [ -z $RESULT ]; then
  exit 0
else
  RESULT=$(pid|awk "NR==$RESULT")
  screen -Dr $RESULT
fi

rm $TMPFILE
