#!/bin/bash
TMPFILE=$(mktemp)

makeList()
{
  pid=$(screen -ls|grep $(hostname)|grep 'Detached'|awk -F. '{print $1}'|sed "s/^[ \t]*//")
	for i in $(echo $pid); do
		pstree $i | sed -n "s/^screen/$i/;1p"
	done | awk '{printf("%5d %s\n", NR,$0)}'
}

if [[ -z $(makeList) ]]; then
  echo "There are no detached screens on $(hostname)."
  exit 1
else
	dialog --keep-tite --menu "Choose one:" 15 70 10 \
	    $(makeList) 2>$TMPFILE
	RESULT=$(cat $TMPFILE)
fi

if [ -z $RESULT ]; then
  exit 0
else
  RESULT=$(screen -ls|grep $(hostname)|awk '{print $1}'|awk "NR==$RESULT")
  screen -Dr $(screen -ls|sed -n "$RESULT p"|awk '{print $1}')
fi

rm $TMPFILE
